Repository WildCodeSchool/orleans-0919-php-magasinbleu, pull requests merged in 2019-11, with the labels that each got.

#42 S01 us1 navbar
  public/assets/css/Home/nav.css
  src/View/Home/nav.html.twig
Labels: Fix, Reviewed

#41 S02 us26 universe page
  .gitignore
  public/assets/css/Home/index.css
  public/assets/css/Home/universe.css
  public/assets/css/Product/index.css
  public/assets/css/style.css
  public/assets/uploads/.gitkeep
  src/Controller/ProductController.php
  src/Model/ProductManager.php
  src/View/Home/_universe.html.twig
  src/View/Home/index.html.twig
  src/View/Home/nav.html.twig
  src/View/Product/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#44 S02US26 fix broken links
  public/assets/css/Product/index.css
  src/Model/ProductManager.php
  src/View/Product/index.html.twig
Labels: Reviewed

#45 S02 us3 carousel
  public/assets/css/Home/carousel.css
  public/assets/css/Home/index.css
  public/assets/css/style.css
  public/assets/images/background_carousel.jpg
  src/View/Home/_carousel.html.twig
  src/View/Home/index.html.twig
Labels: Correction done, Reviewed

#47 Dev
  .gitignore
  public/assets/css/Home/carousel.css
  public/assets/css/Home/index.css
  public/assets/css/Home/nav.css
  public/assets/css/Home/universe.css
  public/assets/css/Product/index.css
  public/assets/css/style.css
  public/assets/images/SteamTrain2Colour.svg
  public/assets/images/background_carousel.jpg
  public/assets/images/blue_rails.svg
  public/assets/images/favicon_train_blue.svg
  public/assets/uploads/.gitkeep
  src/Controller/ProductController.php
  src/Model/ProductManager.php
  src/View/Home/_carousel.html.twig
  src/View/Home/_universe.html.twig
  src/View/Home/index.html.twig
  src/View/Home/nav.html.twig
  src/View/Product/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#46 S02 us03 lastproducts
  public/assets/css/Home/index.css
  public/assets/css/Home/lastproducts.css
  public/assets/css/Home/universe.css
  public/assets/css/style.css
  src/Controller/HomeController.php
  src/Model/ProductManager.php
  src/View/Home/_universe.html.twig
  src/View/Home/index.html.twig
  src/View/Home/lastproducts.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#48 S01 us1 navbar
  public/assets/css/Home/index.css
  public/assets/css/Home/mapHours.css
  public/assets/css/Home/nav.css
  src/View/Home/index.html.twig
  src/View/Home/mapHours.html.twig
  src/View/Home/nav.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#49 Dev
  public/assets/css/Home/index.css
  public/assets/css/Home/lastproducts.css
  public/assets/css/Home/mapHours.css
  public/assets/css/Home/nav.css
  public/assets/css/Home/universe.css
  public/assets/css/style.css
  src/Controller/HomeController.php
  src/Model/ProductManager.php
  src/View/Home/_universe.html.twig
  src/View/Home/index.html.twig
  src/View/Home/lastproducts.html.twig
  src/View/Home/mapHours.html.twig
  src/View/Home/nav.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#50 fix css + changement texte défilant
  src/View/Home/_carousel.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#51 Dev
  src/View/Home/_carousel.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#62 fix du carousel
  public/assets/css/Home/carousel.css
  public/assets/css/Home/nav.css
  public/assets/images/background_carousel.jpg
  src/View/Home/_carousel.html.twig
Labels: Reviewed

#63 Dev
  public/assets/css/Home/carousel.css
  public/assets/css/Home/nav.css
  public/assets/images/background_carousel.jpg
  src/View/Home/_carousel.html.twig
Labels: Reviewed

#66 S01 us1 navbar
  public/assets/css/Home/index.css
  public/assets/css/Home/mapHours.css
  src/View/Home/mapHours.html.twig
Labels: Reviewed

#65 S02 us4 article
  public/assets/css/Describe/describe.css
  public/assets/css/Home/footer.css
  public/assets/css/style.css
  src/Controller/ProductController.php
  src/Model/ProductManager.php
  src/View/Home/footer.html.twig
  src/View/Product/describe.html.twig
  src/View/Product/index.html.twig
Labels: Reviewed

#67 mise en plce de l'update produit
  public/assets/css/Admin/updateproduct.css
  src/Controller/AdminProductController.php
  src/Model/BrandManager.php
  src/Model/CategoryManager.php
  src/Model/ProductManager.php
  src/Model/UniverseManager.php
  src/View/AdminProduct/_form.html.twig
  src/View/AdminProduct/edit.html.twig
  src/View/Product/index.html.twig
Labels: Reviewed

#64 S02 us05 filter
  public/assets/css/Home/index.css
  public/assets/css/Home/lastproducts.css
  public/assets/css/Home/nav.css
  public/assets/css/Home/universe.css
  public/assets/css/Product/index.css
  public/assets/css/style.css
  src/Controller/ProductController.php
  src/Model/BrandManager.php
  src/Model/CategoryManager.php
  src/Model/ProductManager.php
  src/Model/UniverseManager.php
  src/View/Home/_carousel.html.twig
  src/View/Home/_universe.html.twig
  src/View/Home/index.html.twig
  src/View/Home/lastproducts.html.twig
  src/View/Home/nav.html.twig
  src/View/Product/index.html.twig
Labels: Reviewed

#70 Formulaire de contact client - Lionel
  public/assets/css/Contact/contact.css
  public/assets/css/Describe/describe.css
  public/assets/css/Home/index.css
  public/assets/css/style.css
  src/Controller/ContactController.php
  src/View/Contact/contact.html.twig
  src/View/Home/footer.html.twig
  src/View/Home/nav.html.twig
  src/View/Product/describe.html.twig
Labels: Reviewed

#71 S03 us6 update brand
  src/Controller/AdminBrandController.php
  src/Controller/AdminProductController.php
  src/Model/BrandManager.php
  src/View/AdminBrand/_form.html.twig
  src/View/AdminBrand/edit.html.twig
Labels: Reviewed

#68 S03 us07 create
  public/assets/css/Admin/product.css
  public/assets/css/Home/index.css
  src/Controller/AdminProductController.php
  src/Model/CategoryManager.php
  src/Model/ProductManager.php
  src/View/AdminProduct/_form.html.twig
  src/View/AdminProduct/add.html.twig
Labels: Reviewed

#72 S03 us09 fix
  public/assets/css/Describe/describe.css
  public/assets/css/Home/lastproducts.css
  public/assets/css/Home/nav.css
  public/assets/css/Product/index.css
  public/assets/css/style.css
  src/Model/BrandManager.php
  src/View/Home/nav.html.twig
  src/View/Product/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#69 delete + fix affichage dernier produits
  public/assets/css/Admin/index.css
  public/assets/css/Home/index.css
  public/assets/css/Home/lastproducts.css
  public/assets/css/Home/mapHours.css
  src/Controller/AdminProductController.php
  src/Model/ProductManager.php
  src/View/AdminProduct/index.html.twig
  src/View/AdminProduct/nav.html.twig
  src/View/Home/index.html.twig
  src/View/Home/lastproducts.html.twig
  src/View/Home/nav.html.twig
  src/View/layoutAdmin.html.twig
Labels: Reviewed

#76 mise en place de l'update category
  src/Controller/AdminCategoryController.php
  src/Model/CategoryManager.php
  src/View/AdminCategory/_form.html.twig
  src/View/AdminCategory/edit.html.twig
Labels: Reviewed

#87 S04 delete brand
  .gitignore
  public/assets/images/interlaced.png
  src/Controller/AdminBrandController.php
  src/Model/BrandManager.php
  src/View/AdminBrand/edit.html.twig
  src/View/AdminBrand/index.html.twig
Labels: Reviewed

#89 mise en place de l'add des marques
  src/Controller/AdminBrandController.php
  src/Model/BrandManager.php
  src/View/AdminBrand/add.html.twig
Labels: Reviewed

#90 S03 us10 formulaire
  composer.json
  composer.lock
  public/assets/css/Contact/contact.css
  src/Controller/ContactController.php
  src/View/Contact/contact.html.twig
  src/View/Home/footer.html.twig
  src/View/Home/nav.html.twig
Labels: Reviewed

#91 S04 us11 delete category
  src/Controller/AdminCategoryController.php
  src/Model/CategoryManager.php
  src/View/AdminCategory/edit.html.twig
  src/View/AdminCategory/index.html.twig
Labels: Reviewed

#96 S03 fix
  public/assets/css/Admin/product.css
  public/assets/css/Home/footer.css
  public/assets/css/Home/index.css
  public/assets/css/Home/nav.css
  src/View/AdminCategory/edit.html.twig
  src/View/AdminProduct/_form.html.twig
  src/View/AdminProduct/add.html.twig
  src/View/AdminProduct/edit.html.twig
Labels: Reviewed

#97 S04 us09 add category
  src/Controller/AdminCategoryController.php
  src/Controller/AdminProductController.php
  src/Model/CategoryManager.php
  src/View/AdminCategory/add.html.twig
  src/View/AdminCategory/index.html.twig
Labels: Reviewed

#98 S04 add uploads
  config/config.php
  src/Controller/AdminProductController.php
  src/Model/ProductManager.php
  src/View/AdminProduct/_form.html.twig
Labels: Reviewed

#100 fix navbar (fixed-top)
  src/View/Home/nav.html.twig
Labels: Reviewed

#101 fix du carousel
  public/assets/css/Home/carousel.css
  public/assets/images/background_carousel.jpg
  src/View/Home/_carousel.html.twig
Labels: Reviewed

#102 S04 delete upload
  src/Controller/AdminProductController.php
Labels: Reviewed

#103 correction redirection du edit brand
  src/Controller/AdminBrandController.php
Labels: Reviewed

#106 S04 fix front carousel
  public/assets/css/Home/carousel.css
  public/assets/images/SteamTrain2Colour.svg
  public/assets/images/background_carousel.jpg
  public/assets/images/background_carousel.webp
  public/assets/images/blue_rails.svg
  public/assets/images/favicon.png
Labels: Reviewed

#104 S04 us16 search
  .gitignore
  public/assets/css/Home/nav.css
  public/assets/css/Product/index.css
  public/assets/css/style.css
  src/Controller/AdminProductController.php
  src/Controller/ProductController.php
  src/Model/ProductManager.php
  src/Model/SearchManager.php
  src/View/AdminProduct/nav.html.twig
  src/View/AdminProduct/search.html.twig
  src/View/Home/nav.html.twig
  src/View/Product/index.html.twig
  src/View/Product/search.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#105 S04 edit upload
  src/Controller/AdminProductController.php
Labels: Reviewed

#107 Conditions ventes footer - Lionel
  public/assets/css/Home/condition.css
  public/assets/css/Home/footer.css
  public/assets/css/Home/index.css
  src/Controller/ConditionController.php
  src/View/Condition/condition.html.twig
  src/View/Home/footer.html.twig
Labels: Reviewed

#108 S04 us00 css fix
  .gitignore
  composer.json
  composer.lock
  config/config.php
  public/assets/css/Home/footer.css
  src/Controller/ContactController.php
  src/View/AdminBrand/add.html.twig
  src/View/AdminBrand/edit.html.twig
  src/View/AdminBrand/index.html.twig
  src/View/AdminCategory/add.html.twig
  src/View/AdminCategory/edit.html.twig
  src/View/AdminCategory/index.html.twig
  src/View/AdminProduct/add.html.twig
  src/View/AdminProduct/edit.html.twig
  src/View/AdminProduct/index.html.twig
  src/View/Email/index.html.twig
  src/View/Home/footer.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#109 S04 us00 fix filter
  public/assets/css/Product/index.css
  src/View/Product/index.html.twig
  src/View/Product/search.html.twig
Labels: Reviewed

#110 S04 refonte
  public/assets/css/Contact/contact.css
  public/assets/css/Home/contact.css
  public/assets/css/Home/mapHours.css
  public/assets/css/style.css
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/View/Contact/contact.html.twig
  src/View/Home/contact.html.twig
  src/View/Home/footer.html.twig
  src/View/Home/index.html.twig
  src/View/Home/mapHours.html.twig
  src/View/Home/nav.html.twig
Labels: Reviewed

#112 S04 fix affichage derniers produits
  public/assets/css/Home/lastproducts.css
  src/Model/ProductManager.php
Labels: Reviewed

#113 fix des pages descriptions produits
  public/assets/css/Describe/describe.css
  src/View/Product/describe.html.twig
Labels: Reviewed

#114 fix des pages admins + ajout du bouton retour sur certaine
  src/View/AdminBrand/add.html.twig
  src/View/AdminBrand/edit.html.twig
  src/View/AdminCategory/add.html.twig
  src/View/AdminCategory/edit.html.twig
  src/View/AdminProduct/add.html.twig
  src/View/AdminProduct/edit.html.twig
Labels: Reviewed

#115 S04 us00 fix w3c
  public/assets/css/style.css
  src/View/Product/index.html.twig
  src/View/layout.html.twig
  src/View/layoutAdmin.html.twig
Labels: Reviewed

#116 Dev
  public/assets/css/style.css
  src/View/Product/index.html.twig
  src/View/layout.html.twig
  src/View/layoutAdmin.html.twig
Labels: Reviewed

#128 S04 us00 fix navbar
  .gitignore
  public/assets/css/Home/nav.css
  public/assets/css/Product/index.css
  src/View/Home/nav.html.twig
  src/View/Product/index.html.twig
  src/View/Product/search.html.twig
Labels: Reviewed

#129 S04 | fix affichage des univers HOMEPAGE
  public/assets/css/Home/lastproducts.css
  public/assets/css/Home/universe.css
  public/assets/css/style.css
  src/View/Home/_universe.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#130 S04 refonte
  public/assets/css/Home/mapHours.css
  src/View/Home/index.html.twig
  src/View/Home/mapHours.html.twig
Labels: Reviewed

#131 S04US00 redirection vers page produit quand un seul resultat de reche…
  .gitignore
  src/Controller/ProductController.php
Labels: Reviewed

#132 Fix product describe
  public/assets/css/Describe/describe.css
  src/View/Product/describe.html.twig
Labels: Reviewed

#133 image intermédiaire entre les univers et les derniers produits
  public/assets/css/Home/index.css
  public/assets/css/Home/intermediary.css
  public/assets/images/intermediary_train1.jpg
  src/View/Home/index.html.twig
Labels: Reviewed

#134 réparation du carousel
  src/View/layout.html.twig
Labels: Reviewed

#136 S04 us cards
  public/assets/css/Home/lastproducts.css
  public/assets/css/Product/index.css
  src/View/Home/lastproducts.html.twig
  src/View/Product/index.html.twig
Labels: Reviewed

#137 retouche du formulaire de contact
  public/assets/css/Home/contact.css
  public/assets/css/Home/index.css
  src/View/Home/contact.html.twig
Labels: Reviewed

#139 S04 fix lastproducts
  public/assets/css/Home/lastproducts.css
Labels: Reviewed

#135 S04 footer mentions
  public/assets/css/Home/nav.css
  public/assets/css/style.css
  src/View/Condition/condition.html.twig
  src/View/Home/footer.html.twig
  src/View/Home/nav.html.twig
Labels: Reviewed

#138 grossissement et uniformisation du h2
  public/assets/css/Home/index.css
  public/assets/css/Home/universe.css
  src/View/Home/contact.html.twig
Labels: Reviewed

#140 S04US00 fix color border
  public/assets/css/Home/nav.css
Labels: Reviewed

#142 reglage affichage produit par ordre alphabétique parti admin
  public/assets/css/Admin/index.css
  src/Model/ProductManager.php
Labels: Reviewed

#143 reglage affichage marque et catégorie par ordre alphabétique coté admin
  src/Model/BrandManager.php
  src/Model/CategoryManager.php
Labels: Reviewed

#144 fix bug affichage derniers produits
  public/assets/css/Home/lastproducts.css
Labels: Reviewed

#145 S04US00 fix conflict duplication
  public/assets/css/Home/nav.css
  src/View/Home/nav.html.twig
Labels: Reviewed

#141 mise en page CGV
  public/assets/css/Home/condition.css
  src/View/Condition/condition.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#146 placement footer sur les pages descriptions produits
  public/assets/css/Describe/describe.css
Labels: Reviewed

#147 fix block Hours/Map/Infos + ordre d'appel
  public/assets/css/Home/index.css
  public/assets/css/Home/mapHours.css
Labels: Reviewed

#148 S04USXX fix link
  src/View/Home/nav.html.twig
Labels: Reviewed

#149 rectif chemin vers bon layout
  src/View/AdminBrand/add.html.twig
  src/View/AdminBrand/edit.html.twig
  src/View/AdminCategory/add.html.twig
  src/View/AdminCategory/edit.html.twig
  src/View/AdminProduct/add.html.twig
  src/View/AdminProduct/edit.html.twig
Labels: Reviewed

#150 changement taille de police dans navbar
  public/assets/css/Home/nav.css
Labels: Reviewed

#151 border bleue retirée
  public/assets/css/Home/index.css
  public/assets/css/Home/lastproducts.css
Labels: Reviewed

#152 S04 fi overflow
  public/assets/css/style.css
Labels: Reviewed

#153 leger changement block Hours/Infos
  public/assets/css/Home/mapHours.css
Labels: Reviewed

#154 Dev
  .gitignore
  public/assets/css/Admin/index.css
  public/assets/css/Describe/describe.css
  public/assets/css/Home/condition.css
  public/assets/css/Home/contact.css
  public/assets/css/Home/index.css
  public/assets/css/Home/intermediary.css
  public/assets/css/Home/lastproducts.css
  public/assets/css/Home/mapHours.css
  public/assets/css/Home/nav.css
  public/assets/css/Home/universe.css
  public/assets/css/Product/index.css
  public/assets/css/style.css
  public/assets/images/intermediary_train1.jpg
  src/Controller/ProductController.php
  src/Model/BrandManager.php
  src/Model/CategoryManager.php
  src/Model/ProductManager.php
  src/View/AdminBrand/add.html.twig
  src/View/AdminBrand/edit.html.twig
  src/View/AdminCategory/add.html.twig
  src/View/AdminCategory/edit.html.twig
  src/View/AdminProduct/add.html.twig
  src/View/AdminProduct/edit.html.twig
  src/View/Condition/condition.html.twig
  src/View/Home/_universe.html.twig
  src/View/Home/contact.html.twig
  src/View/Home/footer.html.twig
  src/View/Home/index.html.twig
  src/View/Home/lastproducts.html.twig
  src/View/Home/mapHours.html.twig
  src/View/Home/nav.html.twig
  src/View/Product/describe.html.twig
  src/View/Product/index.html.twig
  src/View/Product/search.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#155 S04 footer mentions
  src/Controller/AdminProductController.php
  src/View/Home/nav.html.twig
Labels: Reviewed

#156 Dev
  src/Controller/AdminProductController.php
  src/View/Home/nav.html.twig
Labels: Reviewed
